name: sample_app
description: Flutter Sample Project

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  common:
    path: ./common
  provider: ^6.0.1
  url_strategy: ^0.2.0
  tuple: ^2.0.0
  equatable: ^2.0.3
  infinite_scroll_pagination: ^3.1.0

flutter:
  uses-material-design: true